SET SCHEMA MONITOR;

INSERT INTO ITEM_TYPE (ID, NAME) VALUES (1, 'Temperature');
INSERT INTO ITEM_TYPE (ID, NAME) VALUES (2, 'Humidity');
INSERT INTO ITEM_TYPE (ID, NAME) VALUES (3, 'Switch');
INSERT INTO ITEM_TYPE (ID, NAME) VALUES (4, 'Voltage');

-- UTF-8 DEGREE CELSIUS' (0x2103)

-- SENSOR ITEMS

INSERT INTO SENSOR (ID, NODE, VALUE, UNIT, ITEM_TYPE, TIME, NAME, TOPIC) VALUES(1, 'Hallway', 0.0, char(0x2103), 1, now(), 'T', null);
INSERT INTO SENSOR (ID, NODE, VALUE, UNIT, ITEM_TYPE, TIME, NAME, TOPIC) VALUES(2, 'Hallway', 0.0, '%', 2, now(), 'H', null);
INSERT INTO SENSOR (ID, NODE, VALUE, UNIT, ITEM_TYPE, TIME, NAME, TOPIC) VALUES(5, 'Hallway', 0.0, 'V', 4, now(), 'V', null);

INSERT INTO SENSOR (ID, NODE, VALUE, UNIT, ITEM_TYPE, TIME, NAME, TOPIC) VALUES(10, 'Bedroom', 0.0, char(0x2103), 1, now(), 'T', null);
INSERT INTO SENSOR (ID, NODE, VALUE, UNIT, ITEM_TYPE, TIME, NAME, TOPIC) VALUES(11, 'Bedroom', 0.0, '%', 2, now(), 'H', null);
INSERT INTO SENSOR (ID, NODE, VALUE, UNIT, ITEM_TYPE, TIME, NAME, TOPIC) VALUES(12, 'Bedroom', 0.0, 'V', 4, now(), 'V', null);

--  SWITCH ITEMS

INSERT INTO SWITCH (ID, NODE, VALUE, UNIT, ITEM_TYPE, TIME, NAME, TOPIC) VALUES(1, 'Room', 0, 'X', 3, now(), 'S', null);